### ISSUE TITLE
[help] Eslint 版本冲突晚问题

### ISSUE THREAD

**Issue by xyy94813** [easy-temps/vue3-vant-mobile#104]
指定了 eslint v9，但是其他相关依赖大多用的是v8版本。

这里指定9的目的是？
近期是否有解决该问题的计划？

**Comment by xyy94813** [comment]
```
- @antfu/eslint-config: 2.21.1
```

peer dependencies 为 eslint v8。 npm install 会提示报错

**Comment by CharleeWa** [comment]
我看到对等依赖是 `>=8.40.0`
```
"peerDependencies": {
   "eslint": ">=8.40.0",
}
```
所以 `v9` 应该是支持的。

建议使用 `pnpm` 作为项目的包管理器。

**Comment by xyy94813** [comment]
他这个配置，在大版本之间是会报错的。

现在我这边环境原因不太方便使用 pnpm 这类工具

**Comment by CharleeWa** [comment]
了解，先安装 `eslint v8` 解决你的问题。这个项目一开始使用的 `yarn`，后来才使用的 `pnpm`，也许 `npm` 还有其它问题，可以根据提示调整下包依赖。

**Comment by CharleeWa** [comment]
主要考虑到 eslint v9 默认为平面配置，更好的组合；并且它能和 `@antfu/eslint-config` 包一起很好的工作。所以我升级了它。

如果选择降级，也许需要在 .`vscode/settings.json` 添加如下配置：

>  "eslint.experimental.useFlatConfig": true

这个配置，我在升级到 v9 的时候去掉了，因为它默认为平面配置。但是你可能需要设置它才能和现有的配置一起工作。
