### ISSUE TITLE
[feature] 新建页面后不需要重新构建

### ISSUE THREAD

**Issue by xyy94813** [easy-temps/vue3-vant-mobile#105]
Test Case:

1. npm run dev
2. pages 目录下新增页面
3. 点击按钮跳转至新页面路径 ，此时404
目前 pages 下面新建页面，增加路又跳转会404

重新构建后页面会生效

**Comment by CharleeWa** [comment]
@xyy94813 感谢反馈！一般创建新页面，不需要重新启动，但我不知道什么原因。我今天新建了一个干净的模板，`unplugin-vue-router`  可以工作，新的页面不需要重新启动。目前，我还没有找到与此问题关联的原因。

**Comment by xyy94813** [comment]
能否帮忙提供些相关信息，以便我排查和验证问题？

例如 实现该功能的库有？
win和mac 下是否存在差异点？

**Comment by CharleeWa** [comment]
相关的库有两个：`unplugin-vue-router` 和 `vue-router`，不否定其它基础库，比如 Vite 或者 Vue 对热更新的影响。

**Comment by CharleeWa** [comment]
升级到最新版本就可以了！
