### ISSUE TITLE
发布完，经常出现第一次按钮不好点击，点击了没有任何效果

### ISSUE THREAD

**Issue by Superqinqing** [easy-temps/vue3-vant-mobile#111]

**Comment by ljt990218** [comment]
网址多少 👀

**Comment by Superqinqing** [comment]
![image](https://github.com/easy-temps/vue3-vant-mobile/assets/47345142/986652c9-a96c-4781-b953-01c2901c01d9)
发不完第一次会出现zh这样

**Comment by ljt990218** [comment]
> ![image](https://private-user-images.githubusercontent.com/47345142/346062137-986652c9-a96c-4781-b953-01c2901c01d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjk2NzIsIm5iZiI6MTcyMDE2OTM3MiwicGF0aCI6Ii80NzM0NTE0Mi8zNDYwNjIxMzctOTg2NjUyYzktYTk2Yy00NzgxLWI5NTMtMDFjMjkwMWMwMWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA4NDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOWE4ODU0NTU1NzkxYjA4MTdkNGE3ZjhlYWY4MmU1ZDc3Y2Q0NTY5NzRjMmI0MzA1YjYzMjZkYTE4YzUyZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zjT5tRjJj2d8-nqPpZLVJZTHnJxxukd3BculRPA-JUY) 发不完第一次会出现zh这样

需要你发网址出来 我访问看看

**Comment by CharleeWa** [comment]
需要详细的描述一下问题，才能有效的帮助你。建议在本地构建好以后进行预览看看是不是有同样的问题。

**Comment by CharleeWa** [comment]
暂时关闭，有问题请再打开。
