### ISSUE TITLE
TabBar 组件内 获取路由名称为undefined

### ISSUE THREAD

**Issue by sorkhan** [easy-temps/vue3-vant-mobile#132]
在components/TabBar.vue 文件内，获取 ``route.name`` 值时console显示undefined。 如下图。
![image](https://github.com/user-attachments/assets/1c4c6b20-ba3d-4da7-8d22-cd0fd6e4fa28))

**Comment by CharleeWa** [comment]
@sorkhan 感谢反馈，这可能是因为应用初始加载时，路由还没有完全初始化。使用 watch 函数监听一下，就能看到这个过程了。

```typescript
watch(route, () => {
  console.log(route.name)
}, { immediate: true })

// undefined
// xxx name
``` 

我应该加一下判断来处理这种情况。

```typescript
const show = computed(() => {
  if (route.name) {
    return routeWhiteList.includes(route.name)
  }
  return false
})
```
