### ISSUE TITLE
为什么dev环境能正常运行的版本，build的时候会报错导致打包失败

### ISSUE THREAD

**Issue by yunlianwangluo** [easy-temps/vue3-vant-mobile#140]
我们需要在src/components/TabBar.vue做一些修改，增加了一个按钮，同时增加了一个弹出菜单。打包报错代码：
 const el = menuTab.value.$el，错误：
error TS2339: Property '$el' does not exist on type 'HTMLElement'.
25   const el = menuTab.value.$el
然而在运行npm run dev环境时，却是正常的，没有任何问题。增加的特性（弹出菜单）也能正常执行无报错

**Comment by CharleeWa** [comment]
这看起来是类型检查错误。你可以在打包时去掉类型检查试试看，修改 package.json ：

```
"build":"vite build"
```

另外，根据这个错误提示，TS 在打包编译时把 menuTab 实例误认做了一个 HTMLElement，所以你可以对这个组件进行类型声明，告诉 TS 这是 Vue 组件。

我最推荐最后这个办法。如果还有问题，请告诉我。
