### ISSUE TITLE
页面所有文件会一下子全部加载

### ISSUE THREAD

**Issue by zoujinglong666** [easy-temps/vue3-vant-mobile#95]
![image](https://github.com/easy-temps/vue3-vant-mobile/assets/83895241/63c55b6c-d8dd-4392-b790-fec226876b25)

**Comment by CharleeWa** [comment]
这些文件是本地开发环境预编译产生的，属于正常情况。

**Comment by zoujinglong666** [comment]
好的谢谢解答
