### ISSUE TITLE
路由地址发生变化 但是没跳转过去

### ISSUE THREAD

**Issue by zoujinglong666** [easy-temps/vue3-vant-mobile#96]
![image](https://github.com/easy-temps/vue3-vant-mobile/assets/83895241/2142b31f-6ce6-406d-917c-b047d8b8c567)

**Comment by zoujinglong666** [comment]
也不是每次必现 ，感觉跟这个有关
![Snipaste_2024-05-10_10-16-58](https://github.com/easy-temps/vue3-vant-mobile/assets/83895241/febcd233-ef29-4715-bb59-68ec5ea87f53)

**Comment by zoujinglong666** [comment]
![image](https://github.com/easy-temps/vue3-vant-mobile/assets/83895241/cc207b5e-93cb-4c88-9927-05ff4a5cb7a6)

**Comment by ljt990218** [comment]
可以看看https://github.com/easy-temps/vue3-vant-mobile/issues/92，应该是一样的问题，打包部署服务器后，访问没问题

**Comment by zoujinglong666** [comment]
> 可以看看 #92 应该是一样的问题，打包部署服务器后，访问没问题
这个问题也是我提的

**Comment by ljt990218** [comment]
> > 可以看看 #92 应该是一样的问题，打包部署服务器后，访问没问题
> > 这个问题也是我提的

我没注意看是同一个人，你可以现在打包部署服务器试试

**Comment by CharleeWa** [comment]
暂时关闭，有问题请再打开。

**Comment by CharleeWa** [comment]
@zoujinglong666 添加了依赖项预构建，应该可以了！
